#!/bin/bash

if [ $# -ne 1 ]; then
  echo "use: source sw 123456" 1>&2
else


# スイッチ元のアカウント情報
org_account=567856785678
org_name=my-role

# スイッチ先の選択
target=$(gum choose "dev" "stg" "prod" "test")
case $target in
    "test")
        target_account=123412341234
        target_role_name=dev-role
        color_bg=0000FF
        color_fg=00FFFF
        color_title=0000FF
        ;;
    "dev")
        target_account=345634563456
        target_role_name=dev-role
        color_bg=002000
        color_fg=FFFFFF
        color_title=00FF00
        ;;
    *)
        echo "Invalid option"
        exit 1
        ;;
esac


# 既存の環境変数を一時的に削除する
unset AWS_ACCESS_KEY_ID
unset AWS_SECRET_ACCESS_KEY
unset AWS_SESSION_TOKEN

# MFA認証を行い、一時的な認証情報を取得する
RESULT=`aws sts assume-role \
  --role-arn          arn:aws:iam::${target_account}:role/${target_role_name} \
  --serial-number     arn:aws:iam::${org_account}:mfa/${org_name} \
  --role-session-name "AssumeRole-Session" \
  --duration-second   3600 \
  --token-code        $1 \
`

if [ $? -ne 0 ]; then
  echo "STSに失敗しました。MFAを確認してください"
  return
fi

# 環境変数に一時的な認証情報を設定する
export AWS_DEFAULT_REGION=ap-northeast-1
export AWS_ACCESS_KEY_ID=`echo $RESULT | jq -r .Credentials.AccessKeyId`
export AWS_SECRET_ACCESS_KEY=`echo $RESULT | jq -r .Credentials.SecretAccessKey`
export AWS_SESSION_TOKEN=`echo $RESULT | jq -r .Credentials.SessionToken`

# ターミナルのタイトルと背景色を変更する
red=${color_title:0:2}
green=${color_title:2:2}
blue=${color_title:4:2}
echo -ne "\e]1;${target}\a"
echo -ne "\033]1337;SetColors=bg=${color_bg}\a"
echo -ne "\033]1337;SetColors=fg=${color_fg}\a"
echo -ne "\033]6;1;bg;red;brightness;$((16#$red))\a"
echo -ne "\033]6;1;bg;green;brightness;$((16#$green))\a"
echo -ne "\033]6;1;bg;blue;brightness;$((16#$blue))\a"

# 認証情報を確認する
aws sts get-caller-identity

fi
